### ISSUE TITLE
iframe the site into weebly

### ISSUE THREAD

**Issue by meganrm** [allen-cell-animated/cell-catalog#17]
## Use Case

we want to iframe this site into allencell.org 

## Acceptance Criteria

view it the same way we do the current catalog except no content other than the header. The text above the tables is now included in the site instead of being a part of weebly

## Details
the website is https://cell-catalog.allencell.org/disease-catalog/

**Comment by thao-do** [comment]
Same message in Slack: I ran into this issue:

<img width="452" alt="Screenshot 2024-03-13 at 2 35 47 PM" src="https://github.com/allen-cell-animated/cell-catalog/assets/25212364/c8815aba-c295-469b-9d8d-bd6c490a092d">

<img width="685" alt="Screenshot 2024-03-13 at 2 36 24 PM" src="https://github.com/allen-cell-animated/cell-catalog/assets/25212364/9b3a2b51-0e54-48a6-8aac-da3c3d1d3fbf">
