### ISSUE TITLE
Add data in config file for Stem Cell Characteristics

### ISSUE THREAD

**Issue by meganrm** [allen-cell-animated/cell-catalog#55]
## Use Case

[design](https://www.figma.com/design/kMIJN6BoOkXIhnVUruIHNT/Website-allencell.org?node-id=1198-6040&node-type=FRAME&t=7fKEYYsubyeLzkJ1-0)
 
## Acceptance Criteria

should be an optional object called Stem Cell Characteristics. 

under that, a list of objects that have clone number and %positive cells. They can each be numbers (the front end can format the `cl` and `%`. 

## Details

For now: we won't include the caption with the assumption that it'll be the same for every cell line unless we hear otherwise from @TravisKroeker

**Comment by rugeli** [comment]
Questions to clarify: 
1. Should we include a `title` field along with `clone number` and `% positive cells`, or should the title just default to `Cardiomyocyte Differentiation`? 
2. For the field name, do we want to use `% Positive Cells`, or should it be more descriptive, like `Troponin T, % Positive Cells(n)`?

**Comment by meganrm** [comment]
1. no title needed (you can have a name for the list widget itself) 
2. yeah you can use the whole name for the label
